spring:
    output:
    ansi:
        enabled: DETECT
logging:
  file: logs/diy-decisions-local_profile_app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: DEBUG
    com.diydecisions: INFO
    org.hibernate: DEBUG